title: "Shell Novice"
slug: "shell-novice"
carpentry: "swc"

remote_theme: carpentries/carpentries-theme

markdown: kramdown
highlighter: rouge

collections:
  episodes:
    output: true
    permalink: /:path/index.html
  extras:
    output: true
    permalink: /:path/index.html

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-paginate
